//
// Created by jonnxie on 2022/3/8.
//

#ifndef MAIN_BUILDMACRO_H
#define MAIN_BUILDMACRO_H

#ifndef SHATTER_PLATFORM_WINDOWS
#define SHATTER_PLATFORM_WINDOWS
#endif

#ifndef SHATTER_GRAPHICS_VULKAN
#define SHATTER_GRAPHICS_VULKAN
#endif

#ifndef SHATTER_BUILD_DLL
#define SHATTER_BUILD_DLL
#endif

#endif //MAIN_BUILDMACRO_H
